// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vztihgbszyzucurrijwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6dGloZ2Jzenl6dWN1cnJpand2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNzI2MjEsImV4cCI6MjA2NDk0ODYyMX0.FHn85r_jHUQIQoWB3inX_BUJytyzLad_B3lZS4I6q-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);